IF OBJECT_ID('GAMES..ATTRIBUTE') IS NOT NULL
BEGIN
	DROP TABLE GAMES..ATTRIBUTE
	IF OBJECT_ID('GAMES..ATTRIBUTE') IS NOT NULL
		PRINT '<<< FAILED TO DROP TABLE GAMES..ATTRIBUTE >>>'
	ELSE
		PRINT '<<< DROPPED TABLE GAMES..ATTRIBUTE >>>'
END
GO

CREATE TABLE ATTRIBUTE
(
	ID		INT IDENTITY,
	[NAME]	VARCHAR(25),
	PRIMARY KEY (ID, [NAME])
)

IF OBJECT_ID('GAMES..ATTRIBUTE') IS NOT NULL
BEGIN
	INSERT INTO ATTRIBUTE ([NAME])
	VALUES ('Genre')

	INSERT INTO ATTRIBUTE ([NAME])
	VALUES ('Perspective')

	INSERT INTO ATTRIBUTE ([NAME])
	VALUES ('Setting')

	INSERT INTO ATTRIBUTE ([NAME])
	VALUES ('General Tag')

	PRINT '<<< CREATED TABLE GAMES..ATTRIBUTE >>>'
END
ELSE
	PRINT '<<< FAILED TO CREATE TABLE GAMES..ATTRIBUTE >>>'
GO

