IF OBJECT_ID('GAMES..GENRE') IS NOT NULL
BEGIN
	DROP TABLE GAMES..GENRE
	IF OBJECT_ID('GAMES..GENRE') IS NOT NULL
		PRINT '<<< FAILED TO DROP TABLE GAMES..GENRE >>>'
	ELSE
		PRINT '<<< DROPPED TABLE GAMES..GENRE >>>'
END
GO

CREATE TABLE GENRE
(
	ID		INT IDENTITY,
	[NAME]	VARCHAR(25),
	PRIMARY KEY (ID, [NAME])
)

IF OBJECT_ID('GAMES..GENRE') IS NOT NULL
	PRINT '<<< CREATED TABLE GAMES..GENRE >>>'
ELSE
	PRINT '<<< FAILED TO CREATE TABLE GAMES..GENRE >>>'
GO

IF OBJECT_ID('GAMES..PRODUCT_GENRE') IS NOT NULL
BEGIN
	DROP TABLE GAMES..PRODUCT_GENRE
	IF OBJECT_ID('GAMES..PRODUCT_GENRE') IS NOT NULL
		PRINT '<<< FAILED TO DROP TABLE GAMES..PRODUCT_GENRE >>>'
	ELSE
		PRINT '<<< DROPPED TABLE GAMES..PRODUCT_GENRE >>>'
END
GO

CREATE TABLE PRODUCT_GENRE
(
	PRODUCT_ID	INT IDENTITY,
	GENRE_ID	VARCHAR(25),
	PRIMARY KEY (PRODUCT_ID, GENRE_ID)
)

IF OBJECT_ID('GAMES..PRODUCT_GENRE') IS NOT NULL
	PRINT '<<< CREATED TABLE GAMES..PRODUCT_GENRE >>>'
ELSE
	PRINT '<<< FAILED TO CREATE TABLE GAMES..PRODUCT_GENRE >>>'
GO
