IF OBJECT_ID('GAMES..SETTING') IS NOT NULL
BEGIN
	DROP TABLE GAMES..SETTING
	IF OBJECT_ID('GAMES..SETTING') IS NOT NULL
		PRINT '<<< FAILED TO DROP TABLE GAMES..SETTING >>>'
	ELSE
		PRINT '<<< DROPPED TABLE GAMES..SETTING >>>'
END
GO

CREATE TABLE SETTING
(
	ID		INT IDENTITY,
	[NAME]	VARCHAR(25),
	PRIMARY KEY (ID, [NAME])
)


IF OBJECT_ID('GAMES..SETTING') IS NOT NULL
	PRINT '<<< CREATED TABLE GAMES..SETTING >>>'
ELSE
	PRINT '<<< FAILED TO CREATE TABLE GAMES..SETTING >>>'
GO

IF OBJECT_ID('GAMES..PRODUCT_SETTING') IS NOT NULL
BEGIN
	DROP TABLE GAMES..PRODUCT_SETTING
	IF OBJECT_ID('GAMES..PRODUCT_SETTING') IS NOT NULL
		PRINT '<<< FAILED TO DROP TABLE GAMES..PRODUCT_SETTING >>>'
	ELSE
		PRINT '<<< DROPPED TABLE GAMES..PRODUCT_SETTING >>>'
END
GO

CREATE TABLE PRODUCT_SETTING
(
	PRODUCT_ID		INT IDENTITY,
	SETTING_ID	VARCHAR(25),
	PRIMARY KEY (PRODUCT_ID, SETTING_ID)
)

IF OBJECT_ID('GAMES..PRODUCT_SETTING') IS NOT NULL
	PRINT '<<< CREATED TABLE GAMES..PRODUCT_SETTING >>>'
ELSE
	PRINT '<<< FAILED TO CREATE TABLE GAMES..PRODUCT_SETTING >>>'
GO


INSERT INTO GAMES..SETTING ([NAME])
VALUES ('Fantasy')

INSERT INTO GAMES..SETTING ([NAME])
VALUES ('Sci-Fi')

INSERT INTO GAMES..SETTING ([NAME])
VALUES ('Steampunk')

INSERT INTO GAMES..SETTING ([NAME])
VALUES ('Alternate History')

INSERT INTO GAMES..SETTING ([NAME])
VALUES ('Post-Apocalyptic')

INSERT INTO GAMES..SETTING ([NAME])
VALUES ('Modern')

INSERT INTO GAMES..SETTING ([NAME])
VALUES ('20th Century')

INSERT INTO GAMES..SETTING ([NAME])
VALUES ('Cold War')

INSERT INTO GAMES..SETTING ([NAME])
VALUES ('World War II')

INSERT INTO GAMES..SETTING ([NAME])
VALUES ('World War I')

INSERT INTO GAMES..SETTING ([NAME])
VALUES ('Historical')

INSERT INTO GAMES..SETTING ([NAME])
VALUES ('Ancient')

INSERT INTO GAMES..SETTING ([NAME])
VALUES ('Pre-Historic')


SELECT * FROM GAMES..SETTING