IF OBJECT_ID('GAMES..[STATUS]') IS NOT NULL
BEGIN
	DROP TABLE GAMES..[STATUS]
	IF OBJECT_ID('GAMES..[STATUS]') IS NOT NULL
		PRINT '<<< FAILED TO DROP TABLE GAMES..[STATUS] >>>'
	ELSE
		PRINT '<<< DROPPED TABLE GAMES..[STATUS] >>>'
END
GO

CREATE TABLE [STATUS]
(
	ID		INT IDENTITY,
	[NAME]	VARCHAR(25),
	PRIMARY KEY (ID, [NAME])
)
GO

IF OBJECT_ID('GAMES..[STATUS]') IS NOT NULL
	PRINT '<<< CREATED TABLE GAMES..[STATUS] >>>'
ELSE
	PRINT '<<< FAILED TO CREATE TABLE GAMES..[STATUS] >>>'
GO

IF OBJECT_ID('GAMES..PRODUCT_STATUS') IS NOT NULL
BEGIN
	DROP TABLE GAMES..PRODUCT_STATUS
	IF OBJECT_ID('GAMES..PRODUCT_STATUS') IS NOT NULL
		PRINT '<<< FAILED DROPPING TABLE GAMES..PRODUCT_STATUS >>>'
	ELSE
		PRINT '<<< DROPPED TABLE GAMES..PRODUCT_STATUS >>>'
END
GO

CREATE TABLE PRODUCT_STATUS
(
	PRODUCT_ID	INT,
	STATUS_ID	INT,
	PRIMARY KEY (PRODUCT_ID, STATUS_ID])
)

IF OBJECT_ID('GAMES..PRODUCT_STATUS') IS NOT NULL
	PRINT '<<< CREATED TABLE GAMES..PRODUCT_STATUS >>>'
ELSE
	PRINT '<<< FAILED TO CREATE TABLE GAMES..PRODUCT_STATUS >>>'
GO


INSERT INTO [STATUS](NAME)
VALUES ('Not Played')

INSERT INTO [STATUS](NAME)
VALUES ('Will Not Play')

INSERT INTO [STATUS](NAME)
VALUES ('Maybe')

INSERT INTO [STATUS](NAME)
VALUES ('Plan to Play')

INSERT INTO [STATUS](NAME)
VALUES ('Playing')

INSERT INTO [STATUS](NAME)
VALUES ('Played')

INSERT INTO [STATUS](NAME)
VALUES ('Abandoned')

INSERT INTO [STATUS](NAME)
VALUES ('Completed')


SELECT * FROM GAMES..[STATUS]