IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TAG]') AND type in (N'U'))
BEGIN
	DROP TABLE GAMES..[TAG]
	IF OBJECT_ID('GAMES..TAG') IS NOT NULL
		PRINT '<<< FAILED TO DROP TABLE GAMES..TAG >>>'
	ELSE
		PRINT '<<< DROPPED TABLE GAMES..TAG >>>'
END
GO

CREATE TABLE [TAG]
(
	ID			INT IDENTITY,
	[NAME]		VARCHAR(25),
	ATTRIBUTE	INT,
	PRIMARY KEY (ID, [NAME], ATTRIBUTE)
)

IF OBJECT_ID('GAMES..[TAG]') IS NOT NULL
	PRINT '<<< CREATED TABLE GAMES..TAG >>>'
ELSE
	PRINT '<<< FAILED TO CREATE TABLE GAMES..[TAG] >>>'
GO

IF OBJECT_ID('GAMES..PRODUCT_TAG') IS NOT NULL
BEGIN
	DROP TABLE GAMES..PRODUCT_TAG
	IF OBJECT_ID('GAMES..PRODUCT_TAG') IS NOT NULL
		PRINT '<<< FAILED TO DROP TABLE GAMES..PRODUCT_TAG >>>'
	ELSE
		PRINT '<<< DROPPED TABLE GAMES..PRODUCT_TAG >>>'
END
GO

CREATE TABLE PRODUCT_TAG
(
	PRODUCT_ID	INT,
	TAG_ID		INT,
	PRIMARY KEY (PRODUCT_ID, TAG_ID)
)

IF OBJECT_ID('GAMES..PRODUCT_TAG') IS NOT NULL
	PRINT '<<< CREATED TABLE GAMES..PRODUCT_TAG >>>'
ELSE
	PRINT '<<< FAILED TO CREATE TABLE GAMES..PRODUCT_TAG >>>'
GO


INSERT INTO GAMES..[TAG] ([NAME], ATTRIBUTE)
VALUES ('Fantasy', 3)

INSERT INTO GAMES..[TAG] ([NAME], ATTRIBUTE)
VALUES ('Sci-Fi', 3)

INSERT INTO GAMES..[TAG] ([NAME], ATTRIBUTE)
VALUES ('Steampunk', 3)

INSERT INTO GAMES..[TAG] ([NAME], ATTRIBUTE)
VALUES ('Alternate History', 3)

INSERT INTO GAMES..[TAG] ([NAME], ATTRIBUTE)
VALUES ('Post-Apocalyptic', 3)

INSERT INTO GAMES..[TAG] ([NAME], ATTRIBUTE)
VALUES ('Modern', 3)

INSERT INTO GAMES..[TAG] ([NAME], ATTRIBUTE)
VALUES ('20th Century', 3)

INSERT INTO GAMES..[TAG] ([NAME], ATTRIBUTE)
VALUES ('Cold War', 3)

INSERT INTO GAMES..[TAG] ([NAME], ATTRIBUTE)
VALUES ('World War II', 3)

INSERT INTO GAMES..[TAG] ([NAME], ATTRIBUTE)
VALUES ('World War I', 3)

INSERT INTO GAMES..[TAG] ([NAME], ATTRIBUTE)
VALUES ('Historical', 3)

INSERT INTO GAMES..[TAG] ([NAME], ATTRIBUTE)
VALUES ('Ancient', 3)

INSERT INTO GAMES..[TAG] ([NAME], ATTRIBUTE)
VALUES ('Pre-Historic', 3)


INSERT INTO GAMES..[TAG] ([NAME], ATTRIBUTE)
VALUES ('Isometric', 2)

INSERT INTO GAMES..[TAG] ([NAME], ATTRIBUTE)
VALUES ('First-Person', 2)

INSERT INTO GAMES..[TAG] ([NAME], ATTRIBUTE)
VALUES ('Third-Person', 2)

INSERT INTO GAMES..[TAG] ([NAME], ATTRIBUTE)
VALUES ('Top-Down', 2)

INSERT INTO GAMES..[TAG] ([NAME], ATTRIBUTE)
VALUES ('2D', 2)

INSERT INTO GAMES..[TAG] ([NAME], ATTRIBUTE)
VALUES ('Side-Scroller', 2)

INSERT INTO GAMES..[TAG] ([NAME], ATTRIBUTE)
VALUES ('3D Overview', 2)

INSERT INTO GAMES..[TAG] ([NAME], ATTRIBUTE)
VALUES ('Side View', 2)

INSERT INTO GAMES..[TAG] ([NAME], ATTRIBUTE)
VALUES ('Text', 2)

INSERT INTO GAMES..[TAG] ([NAME], ATTRIBUTE)
VALUES ('Text w/Image', 2)


SELECT * FROM [TAG]